### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/issuer-registry-client#2]
Please populate the README to describe what this code does, how it can be used, and any security concerns.

**Comment by kayaelle** [comment]
Are we still using this repo?

**Comment by dmitrizagidulin** [comment]
> Please populate the README to describe what this code does, how it can be used, and any security concerns.

Addressed by PR #2, closing.

> Are we still using this repo?

Yes, we use it in LCW and verifier plus.
